prompt = """Summarise the information by selecting and reporting the main features, make comparisons where relevant.
The essay part should consist of MAXIMALLY 190 words!!! 
Use IELTS Academic Band 9 vocabulary.
Avoid repetition.
Don't replicate provided Examples!
Use given structured output:
    1. Graph description
    2. Body paragraphs (2-3 separate paragraps)
    3. Overview of the data

Example 1.
    
<TITLE_1>: "Comparison of Energy Production in France in two years"
[IMAGE_1]

Follow given structured input:
1. <Describe a graph:>
"The two pie charts illustrate the proportion of five sources of energy production (coal, gas, nuclear, petrol and other sources) in France in two years (1995 and 2005)."

2. <Find the key points and trends:>

Paragraph 1:
"Energy produced by coal comprised of 29.80% in 1995 and by 2005, it increased by about 1% to 30.9%. Likewise, the amount of energy generated by gas went up by approximately 1% from 29.63% in the first year to 30.1% by the final year. The use of nuclear power rose significantly from 6.40% in 1995 to 10.10% in 2005. Other sources of energy production accounted for 4.90% but then climbed to 9.10%."

Paragraph 2: 
"Petrol, on the other hand, produced 29.27% of all energy in 1995 but 10 years later only 19.55% of energy came from this source."

3. <Write a summary of presented data:>
"Overall, in both years coal and gas accounted for over half of all energy production, while the least was other energy sources. There was only a very minimal increase in production from gas and coal, whereas nuclear and other sources almost doubled. Petrol was the only energy source to decrease over the period."

Example 2.

<TITLE_2>: "Employment sectors of graduates from Brighton University in 2019."
[IMAGE_2]

Follow given structured input:
1. <Describe a graph:>
"The pie chart illustrates the career choices of Brighton University's 2019 graduates, giving the percentages who worked in each of various sectors after finishing university."

2. <Find the key points and trends:>

Paragraph 1: 
"Just under half the students went into industry, with service industries attracting more Brighton graduates than any other sector by far — almost a third (33.0%). About half that number (16.3%) took jobs in manufacturing."

Paragraph 2: 
"Politics and public service were the next most popular choice, accounting for nearly a fifth of graduates. Just over 12% went into politics and a further 5.6% chose the civil service. The other significant career choices were education (about 15%) and two others: transportation and warehousing, with 7.8%; and science and technology with 7.3%."

Paragraph 3:
"The least popular choices included work in the charitable sector and careers in sport, both of which were chosen by well under 1% of graduates. Finally, 2.8% entered work in other, unspecified, sectors."

3. <Write a summary of presented data:>
"Overwhelmingly, industry and government were the most popular employment sectors, far surpassing all other types of employment."


Example 3.
<TITLE_3>: "Percentage of Brtitish Students able to speak languages other than English in two given years."
[IMAGE_3]

Follow given structured input:
1. <Describe a graph:>
"The pie charts display the percentages of British students from one English university who were able to speak languages other than English in 2000 and 2010."

2. <Find the key points and trends:>

Paragraph 1: 
"Those who spoke only Spanish accounted for the greatest proportions of students in both 2000 and 2010, at 30 and 35 percent respectively. With an increase to 20 and 15 percent, those who spoke another language and those who spoke two other languages became the second and third largest groups in 2010. The proportion of those who spoke no additional languages, in comparison, dropped by half to only 10 percent."

Paragraph 2: 
"Of those who were able to speak other languages, French-only speakers were the only group whose proportion experienced a decline from 15 to 10 percent, while the proportion of German-only speakers stayed at 10 percent."


3. <Write a summary of presented data:>
"Overall, the proportion of students who were able to speak additional languages went up in 2010, with Spanish being the most commonly spoken one in both years."

Answer.

<TITLE_LAST>: "{title}"
[{image_name}].
Follow given structured input:
"""